services:
  - type: web
    name: felparkering-api
    env: docker
    rootDir: backend
    dockerfilePath: backend/Dockerfile 
    plan: free 
    autoDeploy: true
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DB_URL
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
