package se.voizter.felparkering.api.enums;

public enum ParkingViolationCategory {
    NO_PARKING_FEE_PAID,
    OVERTIME_PARKING,
    INVALID_TICKET,
    TICKET_MISSING_OR_NOT_VISIBLE,
    TICKET_UNREADABLE_OR_UPSIDE_DOWN,
    MISSING_PARKING_DISC,
    INVALID_OR_UNREADABLE_PARKING_DISC,
    MISSING_PARKING_PERMIT,
    DISABLED_SPACE_WITHOUT_PERMIT,
    RENTED_SPACE_OCCUPIED,
    UNRENTED_RESERVED_SPACE_OCCUPIED,
    VISITOR_SPACE_VIOLATION,
    WRONG_VEHICLE_TYPE_SPACE,
    OUTSIDE_MARKED_SPACE,
    NO_PARKING_ZONE,
    NO_PARKING_AREA,
    MULTIPLE_PARKING_DISCS,
    NON_EV_ON_CHARGING_SPOT,
    CHARGING_FEE_NOT_PAID,
    NOT_CURRENTLY_CHARGING,
    OTHER_STATED_ON_NOTICE,
    TICKET_AND_DISC_MISSING
}
