export const parkingCategories = [
    { label: "Parking fee not paid", value: "NO_PARKING_FEE_PAID" },
    { label: "Parking beyond allowed time", value: "OVERTIME_PARKING" },
    { label: "Invalid parking ticket", value: "INVALID_TICKET" },
    { label: "Valid ticket missing or not visible", value: "TICKET_MISSING_OR_NOT_VISIBLE" },
    { label: "Ticket not readable or upside down", value: "TICKET_UNREADABLE_OR_UPSIDE_DOWN" },
    { label: "Parking disc missing", value: "MISSING_PARKING_DISC" },
    { label: "Parking disc misconfigured or unreadable", value: "INVALID_OR_UNREADABLE_PARKING_DISC" },
    { label: "Valid parking permit missing or not visible", value: "MISSING_PARKING_PERMIT" },
    { label: "Parked in disabled space without permit", value: "DISABLED_SPACE_WITHOUT_PERMIT" },
    { label: "Parked in rented/reserved space", value: "RENTED_SPACE_OCCUPIED" },
    { label: "Parked in reserved but unrented space", value: "UNRENTED_RESERVED_SPACE_OCCUPIED" },
    { label: "Parked in space for visitors", value: "VISITOR_SPACE_VIOLATION" },
    { label: "Parked in space for specific vehicle type", value: "WRONG_VEHICLE_TYPE_SPACE" },
    { label: "Not parked within marked space", value: "OUTSIDE_MARKED_SPACE" },
    { label: "No parking allowed", value: "NO_PARKING_ZONE" },
    { label: "No parking in area", value: "NO_PARKING_AREA" },
    { label: "More than one parking disc visible", value: "MULTIPLE_PARKING_DISCS" },
    { label: "Parked in EV charging spot (non-EV)", value: "NON_EV_ON_CHARGING_SPOT" },
    { label: "Charging fee not paid", value: "CHARGING_FEE_NOT_PAID" },
    { label: "Vehicle not currently charging", value: "NOT_CURRENTLY_CHARGING" },
    { label: "Other reason stated on notice", value: "OTHER_STATED_ON_NOTICE" },
    { label: "Valid ticket and disc both required – both missing", value: "TICKET_AND_DISC_MISSING" }
]