export const parkingCategories = [
    { index: "0", label: "Parking fee not paid", value: "NO_PARKING_FEE_PAID" },
    { index: "1", label: "Parking beyond allowed time", value: "OVERTIME_PARKING" },
    { index: "2", label: "Invalid parking ticket", value: "INVALID_TICKET" },
    { index: "3", label: "Valid ticket missing or not visible", value: "TICKET_MISSING_OR_NOT_VISIBLE" },
    { index: "4", label: "Ticket not readable or upside down", value: "TICKET_UNREADABLE_OR_UPSIDE_DOWN" },
    { index: "5", label: "Parking disc missing", value: "MISSING_PARKING_DISC" },
    { index: "6", label: "Parking disc misconfigured or unreadable", value: "INVALID_OR_UNREADABLE_PARKING_DISC" },
    { index: "7", label: "Valid parking permit missing or not visible", value: "MISSING_PARKING_PERMIT" },
    { index: "8", label: "Parked in disabled space without permit", value: "DISABLED_SPACE_WITHOUT_PERMIT" },
    { index: "9", label: "Parked in rented/reserved space", value: "RENTED_SPACE_OCCUPIED" },
    { index: "10", label: "Parked in reserved but unrented space", value: "UNRENTED_RESERVED_SPACE_OCCUPIED" },
    { index: "11", label: "Parked in space for visitors", value: "VISITOR_SPACE_VIOLATION" },
    { index: "12", label: "Parked in space for specific vehicle type", value: "WRONG_VEHICLE_TYPE_SPACE" },
    { index: "13", label: "Not parked within marked space", value: "OUTSIDE_MARKED_SPACE" },
    { index: "14", label: "No parking allowed", value: "NO_PARKING_ZONE" },
    { index: "15", label: "No parking in area", value: "NO_PARKING_AREA" },
    { index: "16", label: "More than one parking disc visible", value: "MULTIPLE_PARKING_DISCS" },
    { index: "17", label: "Parked in EV charging spot (non-EV)", value: "NON_EV_ON_CHARGING_SPOT" },
    { index: "18", label: "Charging fee not paid", value: "CHARGING_FEE_NOT_PAID" },
    { index: "19", label: "Vehicle not currently charging", value: "NOT_CURRENTLY_CHARGING" },
    { index: "20", label: "Other reason stated on notice", value: "OTHER_STATED_ON_NOTICE" },
    { index: "21", label: "Valid ticket and disc both required – both missing", value: "TICKET_AND_DISC_MISSING" }
]