name: CI (Java)

on:
    push:
        branches: ["**"]
    pull_request:
        branches: ["**"]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v5

            -   name: Setup JDK
                uses: actions/setup-java@v4
                with:
                    java-version: '17'
                    distribution: 'temurin'
            
            -   name: Setup Gradle
                uses: gradle/actions/setup-gradle@017a9effdb900e5b5b2fddfb590a105619dca3c3

            -   name: Build and test with Gradle
                run: ./gradlew --no-daemon clean test
                working-directory: backend

            -   name: Upload test results
                if: always()
                uses: actions/upload-artifact@v4
                with:
                    name: gradle-test-reports-java-17
                    path: |
                        **/build/reports/tests/**
                        **/build/test-results/**
                    if-no-files-found: ignore